mybatis:
  type-aliases-package: mna.homespital.dto
  config-location: classpath:mybatis-config.xml

spring:
  mail:
  host: smtp.gmail.com
  port: 587
  username: homespital77
  password: Ghomespital7!
  properties:
  smtp:
  auth: true
  timeout: 5000
  starttls:
  enable: true

  datasource:
    url: "jdbc:mysql://127.0.0.1:3316/homespital?useSSL=false&autoReconnection=true"
    username: mulcam2
    password: 1234
    hikari:
      maxLifetime: 20000
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB



server:
  port: ${port:8080}


