mybatis:
  type-aliases-package: mna.homespital.dto
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3316/homespital?useSSL=false&autoReconnection=true"
    username: mulcam2
    password: 1234
    hikari:
      maxLifetime: 20000
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: ${port:8080}


