spring:
  datasource:
    url: "jdbc:mysql://121.42.13.136:6603/daily-coorder"
    username: test
    password: 159357@test
    hikari:
      maxLifetime: 20000
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: ${port:8080}
